config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :users
  root "articles#index"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'healthcheck', to: 'healthchecks#show'
  #delete "users/:id", to: "users#destroy"
  resources :users
  resources :sessions
  resources :articles do
    resources :comments
  end
  resources :galleries do
    resources :pictures do
      resources :comments
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :pictures, dependent: :destroy
    has_many :picture_comments, through: :pictures
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :gallery
end

app/models/picture_comment.rb
class PictureComment < ApplicationRecord
  belongs_to :picture
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    #validates :password, length: { minimum: 6 }, allow_blank: true
    #attr_accessor :email, :password, :password_confirmation
    validates_uniqueness_of :email
    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize, only: [:edit, :update]
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    require "google/cloud/bigquery"
    @article = Article.find(params[:id])
    @service = Google::Cloud::Bigquery.new(
      project_id: "playground-355706",
      scope: [
        'https://www.googleapis.com/auth/bigquery.readonly',
        'https://www.googleapis.com/auth/bigquery.insertdata'
      ]
    )
    dataset = @service.dataset "dataset"
    table = dataset.table "tatatable"
    rows = [
        {
            "first_name" => "Anna",
            "last_name" => "Jenkins",
            "email" => "test@gmail.com",
            "gender" => "Female",              
            "ip_address" => "0.0.0.0"
        }
    ]
    table.insert rows
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def create
    @gallery = Gallery.find(params[:gallery_id])
    redirect_to gallery_path(@gallery)
  end

  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @gallery.destroy
    redirect_to gallery_path(@gallery), status: 303
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  # private
  #   def comment_params
  #     params.require(:comment).permit(:commenter, :body, :status)
  #   end
end

app/controllers/healthchecks_controller.rb
class HealthchecksController < ApplicationController
def show
    head :ok
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def index
      @users = User.all
    end
      
    def create
      @user = User.new(user_params)
      if @user.save!
        session[:user_id] = @user.id
        redirect_to root_url, notice: "Thank you for signing up!"
      else
        render "new"
      end
    end

    def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to articles_url
    end
      
    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>

    <div>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>

  <% end %>
  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Site Title - Articles</title>
	<meta charset="utf-8">
	<link rel="stylesheet" href="style.css" type="text/css">
</head>
<body>
	<header>
		<div class="horizontally-aligned header-content">
			<h1 class="width-70">
				<a href="">Site Title</a>
			</h1>
			<div class="width-15">
				<a href="" class="header-link">Sign Up</a>
			</div>
			<div class="width-15">
				<a href="" class="header-link">Log In</a>
			</div>
		</div>
	</header>
	<main class="horizontally-aligned">
		<h2>Articles</h2>
		<div>Our blog has 7 articles and counting!</div>
		<ul>
			<li class="blog-post">
				<a href="">
					<img src="1.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>British Shorthair</div>
					</a>
					<div>The British Shorthair is the pedigreed version of the traditional British domestic cat, with a distinctively stocky body, dense coat, and broad face. The most familiar colour variant is the "British Blue", with a solid grey-blue coat, orange eyes, and a medium-sized tail.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="2.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>Cheshire Cat</div>
					</a>
					<div>The Cheshire Cat is a fictional cat popularised by Lewis Carroll in Alice's Adventures in Wonderland and known for its distinctive mischievous grin. While now most often used in Alice-related contexts, the association of a "Cheshire cat" with grinning predates the 1865 book.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="3.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>Scottish Fold</div>
					</a>
					<div>The Scottish Fold is a breed of domestic cat with a natural dominant gene mutation that affects cartilage throughout the body, causing the ears to "fold", bending forward and down towards the front of the head, which gives the cat what is often described as an "owl-like" appearance.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="4.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>Scottish Straight</div>
					</a>
					<div>The Scottish Straight is one of the feline breeds that make up the Scottish Breed Group, along with the beloved Scottish Fold. More specifically, according to The International Cat Association (TICA), the Scottish Breed Group consists of the longhair Scottish Fold and the shorthair Scottish Fold, as well as the longhair Scottish Straight and the shorthair Scottish Straight, for a total of four breeds.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="5.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>Persian Cat</div>
					</a>
					<div>The Persian cat is a long-haired breed of cat characterized by its round face and short muzzle. It is also known as the "Persian Longhair" in English-speaking countries. The first documented ancestors of Persian cats were imported into Italy from Persia around 1620.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="6.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>Exotic Shorthair</div>
					</a>
					<div>The Exotic Shorthair is a breed of cat developed as a short-haired version of the Persian. The Exotic is similar to the Persian in many ways, including temperament and conformation, a flat nose and face with the exceptions of the short dense coat.</div>
				</div>
			</li>
			<li class="blog-post">
				<a href="">
					<img src="7.jpg" loading="lazy">
				</a>
				<div class="blog-post-description">
					<a href="">
						<div>American Shorthair</div>
					</a>
					<div>The American Shorthair is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats. According to the Cat Fanciers' Association, in 2020, it was the eighth most popular pedigreed cat in the world.</div>
				</div>
			</li>
		</ul>
		<div class="bottom-buttons">
			<a href="" class="custom-button">New Article</a>
			<a href="" class="custom-button">All Users</a>
		</div>
	</main>
	<footer>
		<div class="horizontally-aligned footer-content">© 2022 Some Company. All rights reserved.</div>
	</footer>
</body>
</html>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "All Articles", articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>

    <p>
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>

  <% end %>
  

app/views/galleries/index.html.erb
<h1>Galleries</h1>
<link href='style.css' rel='stylesheet'>

Our blog has <%= Gallery.count %> galleries

<ul>
  <% @galleries.each do |gallery| %>
    <% unless gallery.archived? %>
      <li>
        <%= link_to gallery.title, gallery %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "Add Gallery", new_gallery_path %>

app/views/galleries/show.html.erb
<h1><%= @gallery.title %></h1>

<p><%= @gallery.body %></p>

<ul>
  <li><%= link_to "Edit", edit_gallery_path(@gallery) %></li>
  <li><%= link_to "Destroy", gallery_path(@gallery), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<%= link_to "All Articles", galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Articles</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>



<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
</head>


<body>
<% if notice.present? %>
<p class="notice notice-top"><%= notice %></p>
<% end %>



<% if alert.present? %>
<p class="notice notice-top is--warning"><%= alert %></p>
<% end %>


<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or
  <%= link_to "Log In", login_path %>
<% end %>

<%= link_to "All Galleries", galleries_path %>
<%= yield %>

<div style="position: absolute; bottom: 8px; right: 8px; color: silver; z-index: 100000; pointer-events: none">
1.0
</div>
</body>
</html>

app/views/users/index.html.erb
<ul>
  <% @users.each do |u| %>
    <li>
      <%= u.email %>
      <br>
      <%= image_tag u.avatar, with: '100px', height: '100px' if u.avatar.attached? %>
      <%=
        link_to "Delete", 
        user_path(u), 
        method: :delete, 
        data: { turbo_confirm: "Really delete this user?", turbo_method: "delete" } 
      %>
    </li>
  <% end %>
</ul>

<%= link_to "All Articles", articles_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>